### PR TITLE
Update NIXPKGS_REV to release-2105

### PR DESCRIPTION
**Pull request by hacklschorsch**
... so I hopefully don't have to watch CircleCI build GHC another time.

Maybe this just works and speeds up CI build times a googol.

### CODE REVIEW

**Comment by exarkun** [comment]
The CircleCI build took >2 hours.  I suppose that's because we only have CircleCI's cache set up here and it is keyed on the nixpkgs revision - therefore this change triggers a pretty comprehensive rebuild.  Is that what you were hoping for?

**Comment by hacklschorsch** [comment]
> therefore this change triggers a pretty comprehensive rebuild. Is that what you were hoping for?

😞 

No, quite the opposite.  I hoped if we switched our NIXPKGs to a "release", we would have faster builds due to all the software lying around pre-built on NixOS servers.  Why do all that "reproducible build" theater when then I have to rebuild all the stuff myself anyway.  The only packages I want rebuilt are our own, all else should be downloaded binaries from some NixOS binary cache. 


This build took [2h 31m 16s](https://app.circleci.com/pipelines/github/PrivateStorageio/PaymentServer/267/workflows/c7f5f272-8cf5-4444-ab9d-5e5384a6c52c/jobs/274).
My other PR (#95) took [2h 16m 50s](https://app.circleci.com/pipelines/github/PrivateStorageio/PaymentServer/266/workflows/3c4fc9b6-2f03-4b23-8e81-1b8c7fdba4d6/jobs/273).

So this is making everything slower, not faster.

We could still want this change to get a more current tool chain, now that we at least have confirmation that the test suite still passes. But I leave that for you to decide.

Our software isn't that large. Why does one build take more than 10 minutes?

**Comment by hacklschorsch** [comment]
(Sorry for messing up our cache, I guess?)

**Comment by exarkun** [comment]
> > therefore this change triggers a pretty comprehensive rebuild. Is that what you were hoping for?
> 
> disappointed
> 
> No, quite the opposite. I hoped if we switched our NIXPKGs to a "release", we would have faster builds due to all the software lying around pre-built on NixOS servers. Why do all that "reproducible build" theater when then I have to rebuild all the stuff myself anyway. The only packages I want rebuilt are our own, all else should be downloaded binaries from some NixOS binary cache.

I think that the underlying cause is that little of the Haskell software we build is actually in the NixOS binary cache.  IOHK has its own ... and we have not configured our CI environment to use the IOHK substituter.  So maybe that would be a good thing to do.

Actually ... I'm a little confused by some of the build output (which Firefox *barely* let me look at, it is so long).  It looks like maybe we're *half* configured to use it?  For example:

```
warning: substituter 'https://hydra.iohk.io' does not have a valid signature for path '/nix/store/26f6k1l7n75ylzblnyi5r1m2lrvsmviy-ghc-8.10.5'
```

Ah.  We tell the `nix build` command to use that substituter, but I guess no one ever said the substituter signing key was *trusted* so nothing actually get used from it...  I guess fixing that will cut a ton of time off the build and make us independent of CircleCI's much less reliable (because they delete it faster than our development cycle goes) cache.

> 
> This build took [2h 31m 16s](https://app.circleci.com/pipelines/github/PrivateStorageio/PaymentServer/267/workflows/c7f5f272-8cf5-4444-ab9d-5e5384a6c52c/jobs/274).
> My other PR (#95) took [2h 16m 50s](https://app.circleci.com/pipelines/github/PrivateStorageio/PaymentServer/266/workflows/3c4fc9b6-2f03-4b23-8e81-1b8c7fdba4d6/jobs/273).
> 
> So this is making everything slower, not faster.
> 
> We could still want this change to get a more current tool chain, now that we at least have confirmation that the test suite still passes. But I leave that for you to decide.

I think this is a good update to make, yea.  Practically, I'm not sure how much we actually use from nixpkgs - but it must be something, even if it's just bash and glibc and such.  Maybe we should try to get the iohk binary substituter working, too, though?

> 
> Our software isn't that large. Why does one build take more than 10 minutes?

Hopefully once we really only build *ours* this'll be much faster!

**Comment by exarkun** [comment]
I think the conclusion here is that using a funny version of nixpkgs is not the real cause of slow build times.  On that premise, I'm going to close this PR.  This does not mean we shouldn't have faster builds - just that this doesn't seem to be a successful strategy to get there.

**Pull request closed without merging**
